[toolchain]
anchor_version = "1.1.2"
solana_version = "3.0.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solcage_lending = "3UmM2kDDvyJMNXULcH2m7ACfSLURWtQKmvW17S97U4At"

[programs.devnet]
solcage_lending = "3UmM2kDDvyJMNXULcH2m7ACfSLURWtQKmvW17S97U4At"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace --lib"
